### ISSUE TITLE
テスト作ろう

### ISSUE THREAD

**Issue by tiwanari** [ompugao/english_words_battle#10]
unittest があると良さそう
python って何が主流なんだろう

**Comment by ompugao** [comment]
noseはよく聞くけどとりあえずunittest?
この手の制限のあるAPIを使うコードのテストって普通はモックサーバとか用意したりするのかな

**Comment by tiwanari** [comment]
QA環境あるとうれしいですね笑

**Comment by tiwanari** [comment]
僕は pytest ってのを使ってるのみたことあります！
[3 Best Python unit testing frameworks as of 2018 - Slant](https://goo.gl/qgHP6k)

**Comment by tiwanari** [comment]
自分では使ってない模様
