### ISSUE TITLE
ライセンスきめよう！

### ISSUE THREAD

**Issue by tiwanari** [ompugao/english_words_battle#7]
ライセンス決めないと利用したい人が困るぞい

**Comment by tiwanari** [comment]
like this: https://github.com/tiwanari/emoticon/issues/13

**Comment by ompugao** [comment]
MIT?
NYSL?

**Comment by tiwanari** [comment]
MITでいいようなー？もう一つはどういうやつです？

**Comment by ompugao** [comment]
煮るなり焼くなり好きにしろライセンス、略してNYSL

**Comment by ompugao** [comment]
まぁMITでいっか

**Comment by tiwanari** [comment]
lol やばそう
 MITで！笑
